// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// First, set up the environment-based configuration
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://eokwdajkgbqvvekuvyup.supabase.co'; // New Supabase Project URL
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVva3dkYWprZ2JxdnZla3V2eXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MTgzMjIsImV4cCI6MjA3ODA5NDMyMn0.fg2R4_Fd2I3gxIRFachjF8RwfizigGpwBI29iS3FLqQ'; // New Anon Key

// Initialize Supabase client with environment variables
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage, // Uses localStorage to persist sessions
    persistSession: true,
    autoRefreshToken: true, // Automatically refresh the session token
  },
});
